language: node_js
node_js:
  - "10.1"
cache:
  - node_modules
install:
  - npm install
before_script:  
  - npm run build
script:
  - npm test
after_success:
  - scripts/getrepo.sh danwdart
  - scripts/getrepo.sh jolharg
  - npm run deploy