language: node_js
node_js:
  - "10.15"
cache:
  - node_modules
env:
  - MOZ_HEADLESS=1
addons:
  firefox: latest
install:
  - npm install
before_script:  
  - scripts/getrepo.sh danwdart
  - scripts/getrepo.sh jolharg
  - npm run build
script:
  - npm test
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_ACCESS_TOKEN
  keep-history: true
  local-dir: .site
  committer-from-gh: true
  fqdn: jolharg.com
  on:
    branch: master